"""Initial schema

Revision ID: 09651f897f9e
Revises: 
Create Date: 2026-07-20 23:27:34.689592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09651f897f9e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('cdl_number', sa.String(length=50), nullable=False),
    sa.Column('cdl_expiry', sa.Date(), nullable=False),
    sa.Column('date_of_hire', sa.Date(), nullable=False),
    sa.Column('home_base', sa.String(length=100), nullable=False),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_DUTY', 'DRIVING', 'OFF_DUTY', 'SLEEPER', 'YARD_MOVE', 'PERSONAL_CONVEYANCE', name='driverstatus'), nullable=False),
    sa.Column('availability', sa.Enum('AVAILABLE', 'LIMITED', 'UNAVAILABLE', 'HOME_TIME', name='driveravailability'), nullable=False),
    sa.Column('hos_drive_remaining', sa.Float(), nullable=False),
    sa.Column('hos_duty_remaining', sa.Float(), nullable=False),
    sa.Column('hos_cycle_remaining', sa.Float(), nullable=False),
    sa.Column('hos_last_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hos_violations', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Float(), nullable=False),
    sa.Column('total_miles_ytd', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('detention_hours_mtd', sa.Float(), nullable=False),
    sa.Column('assigned_truck_id', sa.String(), nullable=True),
    sa.Column('assigned_trailer_id', sa.String(), nullable=True),
    sa.Column('current_load_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdl_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('incident_number', sa.String(length=30), nullable=False),
    sa.Column('incident_type', sa.Enum('BREAKDOWN', 'ACCIDENT', 'WEATHER_DELAY', 'TRAFFIC_DELAY', 'FLAT_TIRE', 'FUEL_ISSUE', 'DOT_INSPECTION', 'CUSTOMER_DELAY', 'DETENTION', 'ROAD_CLOSURE', 'DRIVER_ILLNESS', 'CARGO_ISSUE', 'OTHER', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('driver_id', sa.String(), nullable=True),
    sa.Column('load_id', sa.String(), nullable=True),
    sa.Column('truck_id', sa.String(), nullable=True),
    sa.Column('ai_recommended_action', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_number')
    )
    op.create_table('loads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('load_number', sa.String(length=30), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('origin_state', sa.String(length=2), nullable=False),
    sa.Column('origin_address', sa.String(length=255), nullable=True),
    sa.Column('dest_city', sa.String(length=100), nullable=False),
    sa.Column('dest_state', sa.String(length=2), nullable=False),
    sa.Column('dest_address', sa.String(length=255), nullable=True),
    sa.Column('estimated_miles', sa.Integer(), nullable=False),
    sa.Column('pickup_appointment', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_appointment', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('weight_lbs', sa.Integer(), nullable=False),
    sa.Column('trailer_type_required', sa.Enum('DRY_VAN', 'REEFER', 'FLATBED', 'STEP_DECK', 'TANKER', 'LOWBOY', name='trailertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'AT_PICKUP', 'LOADED', 'AT_DELIVERY', 'DELIVERED', 'CANCELLED', name='loadstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='loadpriority'), nullable=False),
    sa.Column('assigned_driver_id', sa.String(), nullable=True),
    sa.Column('assigned_truck_id', sa.String(), nullable=True),
    sa.Column('assigned_trailer_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_reference', sa.String(length=50), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('load_number')
    )
    op.create_table('trailers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_number', sa.String(length=20), nullable=False),
    sa.Column('trailer_type', sa.Enum('DRY_VAN', 'REEFER', 'FLATBED', 'STEP_DECK', 'TANKER', 'LOWBOY', name='trailertype'), nullable=False),
    sa.Column('length_ft', sa.Integer(), nullable=False),
    sa.Column('capacity_lbs', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='truckstatus'), nullable=False),
    sa.Column('assigned_driver_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_number')
    )
    op.create_table('trucks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('truck_number', sa.String(length=30), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('license_plate', sa.String(length=25), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'IN_TRANSIT', 'MAINTENANCE', 'OUT_OF_SERVICE', name='truckstatus'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_level', sa.Float(), nullable=False),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('assigned_driver_id', sa.String(), nullable=True),
    sa.Column('assigned_trailer_id', sa.String(), nullable=True),
    sa.Column('current_load_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate'),
    sa.UniqueConstraint('vin')
    )
    op.create_index(op.f('ix_trucks_truck_number'), 'trucks', ['truck_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'DRIVER_MANAGER', 'FLEET_MANAGER', 'SAFETY_MANAGER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trucks_truck_number'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_table('trailers')
    op.drop_table('loads')
    op.drop_table('incidents')
    op.drop_table('drivers')
    # ### end Alembic commands ###
