"""update_trailers_table

Revision ID: 58f2aa68498a
Revises: 09651f897f9e
Create Date: 2026-07-21 01:29:00.867385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f2aa68498a'
down_revision: Union[str, None] = '09651f897f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new columns
    op.add_column('trailers', sa.Column('trailer_number', sa.String(length=30), nullable=True))
    op.add_column('trailers', sa.Column('assigned_truck_id', sa.String(), nullable=True))
    op.add_column('trailers', sa.Column('current_location', sa.String(length=200), nullable=True))
    op.add_column('trailers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # Copy unit_number into trailer_number
    op.execute("UPDATE trailers SET trailer_number = unit_number")

    # Now make trailer_number not nullable
    op.alter_column('trailers', 'trailer_number', nullable=False)

    # Create index on trailer_number
    op.create_index(op.f('ix_trailers_trailer_number'), 'trailers', ['trailer_number'], unique=True)

    # Drop old unit_number
    op.drop_constraint('trailers_unit_number_key', 'trailers', type_='unique')
    op.drop_column('trailers', 'unit_number')

    # Fix loads index
    op.drop_constraint('loads_load_number_key', 'loads', type_='unique')
    op.create_index(op.f('ix_loads_load_number'), 'loads', ['load_number'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trailers', sa.Column('unit_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_trailers_trailer_number'), table_name='trailers')
    op.create_unique_constraint('trailers_unit_number_key', 'trailers', ['unit_number'])
    op.alter_column('trailers', 'status',
               existing_type=sa.Enum('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='trailerstatus'),
               type_=postgresql.ENUM('AVAILABLE', 'IN_USE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='truckstatus'),
               existing_nullable=False)
    op.drop_column('trailers', 'updated_at')
    op.drop_column('trailers', 'current_location')
    op.drop_column('trailers', 'assigned_truck_id')
    op.drop_column('trailers', 'trailer_number')
    op.drop_index(op.f('ix_loads_load_number'), table_name='loads')
    op.create_unique_constraint('loads_load_number_key', 'loads', ['load_number'])
    # ### end Alembic commands ###
